### ISSUE TITLE
Incorporate Dependabot PRs

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul-github-labeler-action#22]

**Comment by hannes-ucsc** [comment]
This will require updating the references of this action in other repos. When updating those, investigate if we can use the "latest" version so that we don't have to update the references again when we update the action in the future.

**Comment by hannes-ucsc** [comment]
Please also sync the labels from the Azul repository.

**Comment by achave11** [comment]
Labels have been updated.

**Comment by achave11** [comment]
@hannes-ucsc: "Looks good, thank you!"
